/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gw2InfoViewer.views.events;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import org.gw2InfoViewer.models.Event;

/**
 *
 * @author Robert Smieja
 */
public class EventScrollListPanel extends javax.swing.JScrollPane {
    
    private EventDetailsPanel detailsPanel;
    
    /**
     * Creates new form EventScrollListPanel
     */
    public EventScrollListPanel(EventDetailsPanel detailsPanel) {
        initComponents();
        
        this.detailsPanel = detailsPanel;
    }

    public ListModel getListModel() {
        return this.eventNameList.getModel();
    }

    public void setListModel(ListModel<Event> listModel) {
        this.eventNameList.setModel(listModel);
    }

    public int getIndex() {
        return this.eventNameList.getSelectedIndex();
    }

    public void setIndex(int index) {
        this.eventNameList.setSelectedIndex(index);
    }

//    public Event getSelectedItem(){
//        return (Event) this.eventNameList.getSelectedValue();
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventNameList = new javax.swing.JList();

        eventNameList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Loading..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        eventNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                eventNameListValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getViewport());
        getViewport().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventNameList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventNameList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eventNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_eventNameListValueChanged
        if (eventNameList.getSelectedIndex() >= 0) {
            detailsPanel.setEvent((Event) eventNameList.getSelectedValue());
        }
    }//GEN-LAST:event_eventNameListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList eventNameList;
    // End of variables declaration//GEN-END:variables
}
